/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author ExplodingFreeze
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
#define int long long
#define f(i,a,b) for(int i=(a);i<(b);i++)
const int MOD=1e9+7;
using pii=std::pair<int,int>;
//mt19937 rng(chrono::steady_clock::now().time_since_epoch().count()); <-- PUT IN main()/solve()!

using namespace std;

int k,n,a[1005];
class AMaximumSquare {
public:
	void solve(std::istream& in, std::ostream& out) {
		in >> k;
		f(cases,0,k)
		{
			in >> n;
			f(i,0,n)
				in >> a[i];
			sort(a,a+n,greater<int>());
			int ans=0;
			f(i,0,n)
				ans=max(ans,min(i+1,a[i]));
			out << ans << "\n";
		}
	}
};


int32_t main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	AMaximumSquare solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
