/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author ExplodingFreeze
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
#define int long long
#define f(i,a,b) for(int i=(a);i<(b);i++)
const int MOD=1e9+7;
using pii=std::pair<int,int>;
//mt19937 rng(chrono::steady_clock::now().time_since_epoch().count()); <-- PUT IN main()/solve()!

using namespace std;

int k,n;
string s,t;
class B1CharacterSwapEasyVersion {
public:
	void solve(std::istream& in, std::ostream& out) {
		in >> k;
		f(cases,0,k)
		{
			in >> n >> s >> t;
			int cnt=0,pos0=-1,pos1=-1,possible=1;
			f(i,0,n)
				if(s[i]!=t[i])
				{
					cnt++;
					if(cnt>2)
					{
						possible=0;
						break;
					}
					else if(cnt==1)
						pos0=i;
					else
						pos1=i;
				}
			if(cnt==1||!possible||!(s[pos0]==s[pos1]&&t[pos1]==t[pos0]))
			{
				out << "No\n";
				continue;
			}
			else
				out << "Yes\n";
		}
	}
};


int32_t main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	B1CharacterSwapEasyVersion solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
