#pragma GCC optimize("Ofast")
#pragma GCC optimize("O3")
#pragma GCC optimize("unroll-loops")
#pragma GCC target("sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,avx,tune=native")
#include <bits/stdc++.h>
#define int long long int
using namespace std;

//Solution generated by Ashish on 06-11-2019 at 20:36:34

void desperate_optimization(bool submitting=true,int precision=10)
{
  if(!submitting) return;
  ios_base::sync_with_stdio(false);
  cin.tie(0);
  cout.tie(0);
  cout.setf(ios::fixed);
  cout.setf(ios::showpoint);
  cout.precision(precision);
}

int32_t main()
{
  desperate_optimization(true);
  int k;
  cin>>k;
  while(k--)
  {
  	int n;
  	cin>>n;
  	string s,t;
  	cin>>s>>t;
  	vector<int> mismatch;
  	for(int i=0;s[i];i++)
  	{
  		if(s[i]!=t[i]) {mismatch.push_back(i);}
  	}
  	if(mismatch.size()>2) {cout<<"No\n"; continue;}
  	if(mismatch.size()==1) {cout<<"No\n"; continue;}
  	if(mismatch.size()==0) {cout<<"Yes\n"; continue;}
  	int m1=mismatch[0],m2=mismatch[1];
  	if(s[m1]==s[m2] && t[m1]==t[m2]) {cout<<"Yes\n"; continue;}
  	else cout<<"No\n";
  }


  return 0;
}
