#pragma GCC optimize("Ofast")
#pragma GCC optimize("O3")
#pragma GCC optimize("unroll-loops")
#pragma GCC target("sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,avx,tune=native")
#include <bits/stdc++.h>
#define int long long int
using namespace std;

//Solution generated by Ashish on 06-11-2019 at 20:36:34

void desperate_optimization(bool submitting=true,int precision=10)
{
  if(!submitting) return;
  ios_base::sync_with_stdio(false);
  cin.tie(0);
  cout.tie(0);
  cout.setf(ios::fixed);
  cout.setf(ios::showpoint);
  cout.precision(precision);
}

int32_t main()
{
  desperate_optimization(true);
  int t;
  cin>>t;
  while(t--)
  {
  	int n;
  	cin>>n;
  	vector<int> input(n);
  	for(auto& itr:input) cin>>itr;
  	int answer=0;
  	sort(input.begin(), input.end());
  	for(int i=n-1;i>=0;i--)
  	{
  		answer=max(answer,min(input[i],n-i));
  	}
  	cout<<answer<<'\n';
  }


  return 0;
}
