/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Himanshu Bhadani
 */

#include<iostream>
#include<fstream>
#include<climits>
#include<vector>
#include<string>
#include<cmath>
#include<utility>
#include<algorithm>
#include<iomanip>
#include<map>
#include <set>
#include <queue>
#include <stack>
#define ll long long
#define sil(x)  int x;in>>x;while(x--)
#define sid(n)   int n;in>>n
#define si(x) in>>x
#define s(x) string x;in>>x;
#define fl(m,n) for(  int i=m;i<n;i++)
#define flr(n,m) for( int i=n;i>=m;i--)
#define wl(q) while(q--)
#define P(A,B) std::pair<A,B>
#define V(A) std::vector<A>
#define pb push_back
ll M= 1000000000+7;
class CIvanTheFoolAndTheProbabilityTheory {
public:
	void solve(std::istream& in, std::ostream& out) {
	    ll m,n;in>>m>>n;
	    ll ar[std::max(m,n)+1];//={0};
	    ar[0]=1,ar[1]=1;
	    fl(2,std::max(m,n)+1){
	        ar[i]=(ar[i-1]+ar[i-2])%M;
	    }
	    out<<(((((ar[m]+ar[n]-1)%M)+M)%M)*2)%M;
	}
};


int main() {
    std::ios_base::sync_with_stdio(false);
	CIvanTheFoolAndTheProbabilityTheory solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
