/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author ExplodingFreeze
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
#define int long long
#define f(i,a,b) for(int i=(a);i<(b);i++)
const int MOD=1e9+7;
using pii=std::pair<int,int>;
//mt19937 rng(chrono::steady_clock::now().time_since_epoch().count()); <-- PUT IN main()/solve()!

using namespace std;

int t,a,b,c,d,k,x,y;
class APensAndPencils {
public:
	void solve(std::istream& in, std::ostream& out) {
		in >> t;
		f(cases,0,t)
		{
			in >> a >> b >> c >> d >> k;
			x=(a/c)+(a%c!=0);
			y=(b/d)+(b%d!=0);
			if(x+y<=k)
				out << x << " " << y << "\n";
			else
				out << "-1\n";
		}
	}
};


int32_t main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	APensAndPencils solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
