/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author indy256
 */

#include <bits/stdc++.h>

using namespace std;

int pow_mod(int x, int n, int mod) {
    int res = 1;
    for (long long p = x; n > 0; n >>= 1, p = (p * p) % mod)
        if ((n & 1) != 0)
            res = (int) (res * p % mod);
    return res;
}

void solve(istream &in, ostream &out) {
    int n, m;
    in >> n >> m;
    int mod = 1000'000'007;

    int x = pow_mod(2, m, mod);
    x = (x - 1 + mod) % mod;
    int y = pow_mod(x, n, mod);
    out << y << '\n';
}


int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solve(in, out);
}
