/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author indy256
 */

#include <bits/stdc++.h>

using namespace std;

void solve(istream &in, ostream &out) {
    int t;
    in >> t;
    while (t--) {
        int a, b, c;
        in >> a >> b >> c;
        int cnt2 = min(b, c / 2);
        int res = cnt2 * 3;
        b -= cnt2;
        int cnt1 = min(a, b / 2);
        res += cnt1 * 3;
        out << res << '\n';
    }
}


int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solve(in, out);
}
